#+STARTUP: latexpreview
#+TITLE: SMC RESEARCH PROJECT 2013-2014: Evaluation of Pitch-Class Set Similarity Measures for Tonal Analysis
#+AUTHOR: NICHOLAS HARLEY

* Comparison Table						      :Table:

| Measure     | Theorist         | Date | Cardinality | Type                 |
|-------------+------------------+------+-------------+----------------------|
| [[R-relations]] | Forte            | 1973 | SAME        | IcV                  |
| [[s.i.]]        | Teitelbaum       | 1965 | SAME        | IcV                  |
| [[sf]]          | Lord             | 1981 | SAME        | IcV                  |
| [[REL]]         | Lewin            | 1979 | ANY         | SUBSET (Total)       |
| [[REL2]]        | Lewin            | 1979 | ANY         | IcV                  |
| [[SIM]]         | Morris           | 1979 | ANY*        | IcV                  |
| [[ASIM]]        | Morris           | 1979 | ANY         | IcV                  |
| [[K]]           | Morris           | 1979 | SAME        | IcV                  |
| [[AK]]          | Morris           | 1979 | ANY         | IcV                  |
| [[MEMB2]]       | Rahn             | 1979 | SAME        | SUBSET               |
| [[AMEMB2]]      | Isaacson*        | 1990 | ANY         | SUBSET*              |
| [[ATMEMB]]      | Rahn             | 1979 | ANY         | SUBSET (Total)       |
| [[IcVSIM]]      | Isaacson         | 1990 | ANY         | IcV                  |
| [[ISIM2]]       | Isaacson         | 1996 | ANY         | IcV                  |
| [[IcVD1]]       | Rogers           | 1992 | ANY         | IcV                  |
| [[IcVD2]]       | Rogers           | 1992 | ANY         | IcV                  |
| [[cos(-)]]      | Rogers           | 1992 | ANY         | IcV                  |
| [[%RELn]]       | Castren          | 1994 | ANY         | SUBSET               |
| [[%25REL2][%REL2]]       | Castren          | 1994 | ANY         | IcV                  |
| [[T%25REL][T%REL]]       | Castren          | 1994 | ANY         | SUBSET (Total)       |
| [[RECREL]]      | Castren          | 1994 | ANY         | SUBSET (Total)       |
| [[ANGLE]]       | Scott & Isaacson | 1999 | ANY         | IcV                  |
| [[SATSIM]]      | Buchler          | 1998 | ANY         | IcV-SATV             |
| [[CSATSIM]]     | Buchler          | 1998 | ANY         | IcV-SATV             |
| [[AvgSATSIM]]   | Buchler          | 1998 | ANY         | SUBSET-SATVn (Total) |
| [[TSATSIM]]     | Buchler          | 1998 | ANY         | SUBSET-SATVn (Total) |
| [[EMB]]         | Lewin            | 1977 | -           | SUBSET               |

* Theoretical Resemblace Models				 :SimilarityMeasures:
** REL								      :Lewin:
FROM: [[Lewin,%201979][Lewin]]
*** Description
    - For each class being compare the subset vector is computed
    - the subset vector is 357 dimensions
      - 6 for IcV then 351 for each correspondin to the embedding all  Tn related sets
    - sub(X,i) is the ith term in the subset vector
*** Formula
     $$ REL ( A,B ) = \frac{\sum_{i=1}^{357}\sqrt{sub(A,i).sub(B,i)} }{\sqrt{\sum_{i=1}^{357}sub(A,i).\sum_{i=1}^{357}sub(B,i)}} $$
** REL2								      :Lewin:
FROM: [[Lewin,%201979-80][Lewin]], 1979-80
*** Description
    - A specialised version of [[REL]] that measures only intervallic similarity
    - criticises Rahns (x_{i}+y_{i}) as "arithmetic awkwardness"
    - Multiplies corresponding IcV entries
    - REL2 increases as corresponding IcV entries increase
    - As cardinality increases, range of REL decreases
    - high level of distinction
    - produces max similarity only when IcVs are identical
*** Formula
    $$ REL_{2}(X,Y) \frac{2\times \sum \sqrt{(x_{i}y_{i})}}{\sqrt(\#X(\#X-1)\#Y(\#Y-1))} $$
** EMB								      :Lewin:
*** Description
    - EMB(A,X) is the number of pitch-class sets in set-class A which are subsets of a given pitch-class set in set-class X.

** IcVSIM							   :Isaacson:
From: [[Isaacson,%201990][Isaacson, 1990]]
*** Description
    - the standard deviation of the entries in the [[IdV]] of two sets
    - Same degree of distinction as [[Teitelbaum,%201965][s.i.]]
    - any cardinality
    - Mathematically IcVSIM is a scalled version of s.i.
*** Formula
    $$ IcVSIM\left(X,Y\right)=\sigma\left(IdV\right) $$
    where 
    $$ IdV=[(y_{1}-x_{1})(y_{2}-x_{2})...(y_{6}-x_{6})] $$
    and
    $$ \sigma =  \sqrt {\frac {\sum (IdV_{i}- \overline {IdV})^{2}}{6}} $$
    where
    $$IdV_{i}$$ is the ith term of the interval-difference vector and
    $$\overline {IdV}$$ is the average (mean) of the terms in the IdV
** ISIM2							   :Isaacson:
FROM: [[Isaacson,%201996][Isaacson]]
*** Description
    - IcV entries are scaled by taking the square root
    - otherwise its the same as [[IcVSIM]]
    - [[Samplaski,%202005][Samplaski]] found ISIM2 to be inconsistent with itself with [[MDS]]
** s.i.								 :Teitelbaum:
*** Description
    - Greater discrimincation than Forte, Morris, Lord
    - same cardinality
    - vlaues approach 0 when the pcsets being compared are in a close intervallic relationship
    - high level of distinction (almost as high as [[Lewin,%201979-80][Lewin]]'s [[REL2]])
    - can compare the intervallic similarity of sets with the same cardinality to a reference
    - evaluable to some degree by MDS, but not very attractive
*** Formula
    $$  s.i.(X,Y) = \sqrt{\sum (x_{i}-y_{i})^{2}} $$
** R-relations							      :Forte:
   - Rn
   - Same cardinality
   - not a complete system (many IcV pairs have no Rn relation
   - See [[Isaacson,%201990][Isaacson]] for criticism
** SIM								     :Morris:
   From: [[Morris,%201979][Morris]]
*** Description

    - sum of the absolute values of the differences between corresponding IcV entries for the sets
    - Produces 15 unique values:
     - four each for trichords and tetrachords
     - three each for pentachords and hexachords

*** Formula
    $$ SIM \left ( X, Y \right ) = \sum_{i = 1}^{6} \left | x_{i} - y_{i} \right | $$   
** ASIM								     :Morris:
   From: [[Morris,%201979][Morris]]
*** Description
   - Any size/cardinality:
     - but there is "diminishing return" as the difference between the cardinalities of the two sets increases
     - values of SIM increase as the difference in cardinality between sets increases
     - ASIM(X,Y): values are weighted by dividing them by the sum of the cardinalities of the sets

*** Formula

    $$ ASIM \left ( X, Y \right ) = \frac{SIM \left ( X, Y \right )}{\left ( \# V \left (X \right ) + \# V \left (Y \right ) \right )} $$
** K								     :Morris:
From: [[Morris,%201979][Morris]]
*** Description

    - Number of ics in common between the sets X and Y
    - It is a function of SIM(X,Y)
    - Rahn prefers k to SIM

*** Formula
    
    $$ k = \frac{\left( \# V  \left( R \right) + \# V  \left( S \right) - SIM  \left( R, S \right) \right)}{2} $$
    Rahn writes it differently (as a funtion of X and Y)
    $$ k\left(X, Y \right) = \frac{\left( \# V  \left( R \right) + \# V  \left( S \right) - SIM  \left( R, S \right) \right)}{2} $$
** AK								       :Rahn:
   From: [[Rahn,%201979][Rahn]]
*** Description
    - absolute or adjusted [[K][k]] (from Morris, comparable to [[ASIM]])
    - ASIM and Ak are closeley relate
*** Fromula
    $$ ak \left( X, Y \right) = \frac{2 \times k \left( X, Y \right)}{\# V \left( X \right) + \# V \left( Y \right) }  $$
    $$ Ak(X,Y)=1-ASIM(X,Y) $$
** MEMB								       :Rahn:
FROM: [[Rahn,%201979][Rahn]]
*** Description
    - [[MEMBn]] counts number of subsets X of size n
    - a subset must be present in both X and Y before it is counted 
    - by setting n to 2 you get [[MEMB2]] (measure of ic similarity)
    - works badly when cardinalities differ greatly
*** Formula
**** MEMBn
     $$ MEMB_{n} \left( J,X,Y \right) = EMB \left( J,X \right) + EMB \left( J,Y \right)  $$
     for all J such that
     $$ \# J = n $$
     and
     $$ EMB \left( J,X \right) > 0 $$
     and 
     $$ EMB \left( J,Y \right) > 0 $$
     so...
     $$ MEMB_{\#X}\left( X,X,Y \right)=EMB\left( X,Y \right) + 1 $$

**** MEMB2
     $$ MEMB_{2}\left(X,Y\right)=\sum_{i=1}^{6}\left(x_{i}+y_{i}\right) $$
     such that $$ \left(x_{i}>0\right) $$ and $$ \left(y_{i}>0\right) $$
** AMEMB2							   :Isaacson:
From: [[Isaacson,%201990][Isaacson]]
*** Description
    - Isaacson describes a scaled version of [[MEMB2]]
    - Applies a normalisation factor equivelant to that used by [[Rahn,%201979][Rahn]] to derive [[ATMEMB]] from [[TMEMB]]
    - range of values decreases as cardinality increases
    - AMEMB increases as cardinality increases - troubling
*** Formula
    $$ AMEMB_{2}=\frac{\sum \left( x_{i}+y_{i} \right)}{\frac{\left(\#X\left(\#X-1\right)+\#Y\left(\#Y-1\right)\right)}{2}} $$
    such that $$ \left(x_{i}>0\right) $$ and $$ \left(y_{i}>0\right) $$
** TMEMB							       :Rahn:
From: [[Rahn,%201979][Rahn]]
*** Description
    - the sum of all [[MEMBn]] (n = 2 to 12)
    - distinguishes between Z-related sets
*** Formula
     $$ TMEMB \left( A,B \right) = \sum_{n=2}^{12}MEMB_{n}\left( X,A,B \right) $$
** ATMEMB							       :Rahn:
FROM: [[Rahn,%201979][Rahn]]
*** Description
    - Absolute/adjjusted version of [[TMEMB]]
    - distinguishes between Z-related sets
*** Formula

     $$ ATMEMB\left(A,B\right)=\frac{TMEMB\left(A,B\right)}{2^{\#A}+2^{\#B}-\left(\#A+\#B+2\right)} $$
** sf								       :Lord:
From: [[Lord,%201981][Lord]]
*** Description
    - half sum of absolute values of the differences between corresponding IcV entries of the sets
    - sf is a subset of [[SIM]]
    - Same cardinality
    - Lords values can be inferred from [[Morris,%201979][Morris]]'
*** Formula
    $$  sf \left ( X,Y \right ) = \frac{ \sum_{i = 1}^{6} \left | x_{i} - y_{i} \right |}{2}  $$
    where X and Y are any pcset from 3 to 9 notes and
    $$ x_{i} = IcV(X)_{i} $$ and $$ y_{i} = IcV(Y)_{i} $$
** ANGLE							   :Isaacson:
*** Description
** %RELn							    :Castren:
FROM: [[Castren,%201994][Castren]]
*** Description
    - compare proportionate subset-class contents of two set-classes
    - uses [[nC%V]] 
*** Formula
    $$ \%REL_n(X,Y)=\frac{\sum_{i=1}^{p}|x_i-y_i|}{2} $$
    where xi and yi are values in the [[nC%V]]
** %REL2							    :Castren:
FROM: [[Castren,%201994][Castren]]
*** Description
    - is castrens modification of [[Lord,%201981][Lord]]'s [[sf]]
    - [[%RELn]] with n = 2
    - thus measures intervallic similarity
** T%REL							    :Castren:
FROM: [[Castren,%201994][Castren]]
*** Description
    - Total percentage RELation
    - is the arithmetic mean of all %RELn values for n=2 to min(#X,#Y)
    - Considered to be a preliminary version of [[RECREL]]
    - Total measure
** RECREL							    :Castren:
FROM: [[Castren,%201994][Castren]]
*** Description
    - examines the similarity between two set-classes by composing a net of pairings of all embeddable subset-classes, both shared and non- shared.
    - RECREL evaluates function [[%25RELn][%RELn]] many times during the process.
    - The final RECREL value is the arithmetic mean of the individual %RELn values.
** SATSIM							    :Buchler:
*** Description
    - SATuration SIMilarity index
    - based on interval-class saturation vectors ([[SATV]])
** CSATSIM							    :Buchler:
*** Description
    - extension of [[SATSIM]]
** TSATSIM							    :Buchler:
*** Description
    - Total subset SATuration SIMilarity index
    - calculated by dividing the sum of the numerators of all SATSIMn comparisons by the sum of the denominators
    - very similar to [[AvgSATSIM]]
** AvgSATSIM							    :Buchler:
*** Description
   - based on subset-class saturation vectors
   - first calculate SATSIMn values (cardinality class n SATuration SIMilarity), n reaching
from 2 to m-1 (m = min[#X,#Y]).
   - The SATSIMn comparisons are made similarly to the comparisons in SATSIM. The final AvgSATSIM value is the arithmetic mean of the individual SATSIMn values
** IcVD1							     :Rogers:
*** Description
    - Modification of [[Morris,%201979][Morris]]'s [[SIM]]
*** Formula
    $$\%REL_2(X,Y)=IcVd_1(X,Y)\times50 $$
** IcVD2							     :Rogers:
*** Description
    - use IcV like geometric vectors is 6D space
    - IcVD2 is the distance between the ends of the two vectors
    - the IcVs are normalised
*** Formula
    $$ IcVD_2(X,Y)=\sqrt{\sum{( \frac{x_i}{\sqrt{\sum(x_i)^2}}}-\frac{y_i}{\sqrt{\sum(y_i)^2}})^2} $$
** cos(-)							     :Rogers:
*** Description
    - is cos of the angle between the normalised IcVs
*** Formula
    $$ Cos\theta(X,Y)=\frac{\sum{x_i.y_i}}{\sqrt{\sum{(x_i)^2}}.\sqrt{\sum{(y_i)^2}}} $$
* Forte, 1973								 :Rn:
  - =The Structure of Atonal Music=
  - [[R-relations]]
* Lord, 1981								 :sf:
  - =Intervallic Similarity Relations in Atonal Set Analysis=
  - [[sf]]
* Morris, 1979							 :SIM:ASIM:K:
  - =A similarity index for pitch-class sets=
  - [[SIM]], [[ASIM]], [[K]]
* Isaacson, 1990					      :IcVSIM:AMEMB2:
  - =Similarity of Interval-Class Content Between Pitch-Class Sets: The IcVSIM Relation=
  - Isaacson Suggests 3 criteria for a similarity measure
    1. provide a distinct value for every pair of sets
    2. be useful (not just usable) for sets of any size
    3. provide a wide range of discrete values
  - on the basis of these criteria he finds the measures of Teitelbaum, Forte, Morris, Rahn, Lewin, Lord to be inadequate
  - Proposes [[IcVSIM]]
* Castren, 1994							:RECREL:%REL:
* Isaacson, 1996						      :ISIM2:
  - =Issues in the study of similarity in atonal music=
  - Good discussion of similarity over all
  - [[ISIM2]]
  - weighted version of IcVSIM
* Lewin, 1979-80 						   :REL:REL2:
  - =A Response to a Response: On PCSet Relatedness=
  - [[REL]], [[REL2]]
* Rahn, 1979 						  :MEMB:TMEMB:ATMEMB:
  - =Relating Sets=
  - [[MEMB]], [[TMEMB]], [[ATMEMB]]
* Scott & Isaacson, 1998					      :ANGLE:
  - *The Interval Angle: A Similarity Measure for Pitch-Class Sets*
  - ANGLE
  - STATEMENT 11
    - can be generalized for figured-bass
    - The new construction can distinguish between
major and minor chords and between different doublings and different inversions of the chords
  - STATEMENT 12
    - ANGLE M 
    - further extension to ANGLE
* Teitelbaum, 1965							 :si:
  - =Intervallic Relations in Atonal Music=
  - [[s.i.]]
* Samplaski, 2005							:MDS:
=Mapping the Geometries of Pitch-Class Set Similarity Measures via Multidimensional Scaling=
** methodology
   - 6 pcset similarity measures investigated
     - *3 interval based*
       1. [[Scott%20&%20Isaacson,%201998][ANGLE]]
       2. [[Isaacson,%201990][IcVSIM]]
       3. [[Isaacson,%201996][ISIM2]]
     - *3 subset based* use subset embedding
       1. [[Castren,%201994][RECREL]]
       2. [[ATMEMB]]
       3. [[AMEMB]]
   - *3 cardinalities* under [[TnI][Tn/I]]-equivelance
     - trichords: 3
     - tetrachords: 4
     - pentachords: 5
     - ratings for each cardinality of set-class separately as well as contiguously grouped together (3+4, 4+5, 3+4+5) were studied
   - [[MDS]] applied to matrices of (dis)similarities
   - based on goodness-of-fit analysis...
     - four-dimensional geometric solutions were found for the icv-based measure
     - five-dimensional solutions were found for the subset based measures
** motivation
   1. Visualisation
      - similarity measures yield alot of data
   2. not satisfied with [[Scott%20&%20Isaacson,%201998][scott and isaacoson]] conclusions about correlation
      - correlations (as single, all-subsuming numbers for pairs of measures) do nothing to show what constructs might underlie the ratings being produced.
   3. geometric visualisation allows a "reality check"
      - there might be problems with a measure's numerical ratings that are not evident from inspection of them
   4. [[MDS%20on%20Pcsets%20using%20distance%20function][see here]]
** Conclusions
   The overall results are generally consistent with the idea that these functions all measure constructs relating to familiar scales (diatonic, hexatonic, octatonic, etc.). The results are also compared with several systems of pcset genera. ISIM2 was found to be inconsistent with itself in terms of the geometries it produced. Several set-classes had coordinates near zero along various dimensions in the derived configurations, indicating that in a formal quantitative sense they do not possess the corresponding musical properties being measured; this may raise questions concerning the relative aesthetic worth of some such set-classes.
** more
   - [[CA]] paragraph 18-19
   - [[robustness]] paragraph 20, paragraphs 52-53
   - [[PMDS]] note
* Forte, 1988							     :genera:
  - =Pitch-Class Set Genera and the Origin of Modern Harmonic Species=
  - [[Samplaski,%202005][Samplaski]] paragraph 58
* Parks, 1989							     :genera:
  - =The Music of Claude Debussy=
  - [[Samplaski,%202005][Samplaski]] paragraph 59-60
* Quinn, 1997 							  :genera:CA:
  - =On Similarity, Relations, and Similarity Relations=
  - [[Samplaski,%202005][Samplaski]] paragraph 61
  - used [[CA]] on ratings from similarity measures
  - found correspondence among measures
  - defined 8 genera
    - there were some "fence sitters"
    - argued strongly for a fuzzy set theory of pcset similarity
* Quinn, 2001								 :CA:
  - =Listening to similarity relations=
  - What constitutes a good similarity measure?
    1. The ways in which we are accustomed to talking about similarity relations are not as productive as they seem to be, and there are better ways to do it.
    2. Comparison of various similarity relations from such a different point of view shows that they are more related to each other, and to a lot of other theory, than they appear to be in traditional modes of discourse.
  - [[Samplaski,%202005][Samplaski]] paragraphs 62-63
    - found clusters using monte carlo analysis
* Regener, 1974
  - =On Allen Forte's Theory of Chords=
  - 
* GLOSSARY
** pc
PITCH-CLASS. A set of all pitches that are enharmonically identical and/or related by any number of octaves. There are twelve pcs, numbered from 0 to 11. pc 0 contains all C naturals, all B sharps, all D double-flats; pc 1 contains all Dbs, all C#s; pc 2 contains all Ds, all C##s, all Ebbs, and so forth-pc 11 which contains all Bs, A##s, and Cbs.
From [[Morris,%201979][Morris]]
** ic
INTERVAL CLASS. A set of all interval that differ by multiples of 12 semi-tones and/or are complementary respect with to the octave. There are six ics, numbered
from 1 to 6. ic 1 contains all minor 2nds, all major 7ths, all diminished octaves, all augmented 8ves, all min 9ths, etc.; ic 2 contains all major 2nds, all dim 3rds, all aug 6ths, all min 7ths, all maj 9ths,etc. -and so forth-ic 6 contains all tritones, and intervals of a tritone plus any amount of octaves. The ic may also be defined as the set of intervals between any of the members of one pc and any of the members of another. The intervals between any D # and any F are all members of ic 2.
From [[Morris,%201979][Morris]]
** set
An unordered collection of pcs without replication. The set (0,3,4) is the same as (0,4,3) and (4,3,0), etc. A particular set may be denoted by a capital letter. For instance, T = (0,3,4). There are 4,096 distinct sets.
From [[Morris,%201979][Morris]]
** SC
SET-CLASS. A collection of sets related to one another by Tn and/or I.
From [[Morris,%201979][Morris]]
** Tn 
Tn TRANSPOSITION by 'n' semitones 'higher'. To transpose a set we add n to each pc in the set; if the sum exceeds 11, we reduce it by 12. If the set (8,5,7) is subjected to T5, the result is 8+5, 5+5, and 7+5 or (1,10,0). If W=(8,5,7), then (1,10,0) may be written T5W.
From [[Morris,%201979][Morris]]
** I
INVERSION. An operation on pcs which sends, 1 to 11 and vice- versa, 2 to 10 and the reverse, 3 to 9, 4 to 8, 5 to 7, while 0 and 6 remain the same. The inversion of the set (6,8,4,3) is (6,4,8,9) (and vice-versa). If (6,8,4,3) = D, then ID = (6,4,8,9).
From [[Morris,%201979][Morris]]
** TnI
Inversion followed by transposition. T5I of (7,9.4) is produced by taking the inversion which is (5,3,8) and transposing it by T5 which results in (10,8,1). If our original set is L, then T5IL= (10,8,1).
From [[Morris,%201979][Morris]]
** Invariance 
A set is invariant if it remains unchanged after transformation under Tn or I or both. T4I of the set H which is (3,1,8) results in invariances since 3 becomes 9+4 or 1, 1 becomes 11+4 or 3, and 8 becomes 4+4 or 8. We say that our set is invariant under T4I. T4H= H
From [[Morris,%201979][Morris]]
** V
INTERVAL-CLASS-VECTOR. A listing of the amount of ics of each type in a particular set. V(Y) is the interval-class-vector associated with the set Y. A V is an array of six numbers square brackets. The first number is called V1 and gives the amount of ic Is in the set; the second number or argument, V2, is the number of ic 2s in the set; etc., to the sixth argument, V6, which gives the number of ic 6s. In the expression, V(B) = [1,1,1,0,0,0], we are asserting the set B has one ic 1, one ic 2, one ic 3, and no ic 4, 5, or 6. The set (5,7,8) could be B. We may determine the V of any set by examining all pairs of pcs in the set, finding the ic for each pair, and registering it in the appropriate argument in the array. If the set R is (8,4,2,0) the ic for 8 and 4 is 4; the ic for 8 and 2 is 6; the ic for 8 and 0 is 4; the ic for 4 and 2 is 2; for 4 and 0 we have 4 and for 2 and 0 we have 2. Thus, V(R) = [0,2,0,3,0,1].
From [[Morris,%201979][Morris]]
** #R
Where R is a set, #R denotes its cardinality, is, the number that of pcs in R.
From [[Morris,%201979][Morris]]
** #(V)R
The number of ics in V(R). Where R contains n pcs (n = #R), 4V(R) is equal to the sum of whole numbers starting with 1 and ending with (n-1). A set of seven pcs has 1+2+3+4+5+6 or 21 ics.
From [[Morris,%201979][Morris]]
** Membership \in
5 \in (8,5,7) d \in R (a pc named d is a member of the set R). 
From [[Morris,%201979][Morris]]
** Inclusion \subset
R \subset T if every pc in set R is also in set T (R is a sub-set of T).
(7,5,8) \subset (8,5,3,7,0)
From [[Morris,%201979][Morris]]
** | x | (Absolute Value) 
Take the positive sign of the expression enclosed in Is. | 5 | = 5; | -7 | = (+)7; | 7-2 | = | 2-7 |.
From [[Morris,%201979][Morris]]
** Genera
   - classical
     - an object either belongs or does not
   - fuzzy
     - an object has a probability of belonging
   - many genera systems have been proposed
     - Ericksson, 1986
     - [[Forte,%201988][Forte, 1988]]
     - [[Parks,%201989][Parks, 1989]]
     - [[Quinn,%201997][Quinn, 1997]]
     - [[Quinn,%202001][Quinn, 2001]]
   - Some dont relate directly to pcsets: e.g., Hanson, 1960; Harris, 1989; Hindemith, 1937/42; Wolpert, 1951, 1972
** Z-Relation
   - Same icv but not related by TnI
** robustness
  - whether changing the set of objects being compared alters the perceived/computed similarity between the original set of objects.
  - "yields consistent relative MDS geometries, save for scaling, regardless of surrounding context" [[Samplaski,%202005][samp]] paragraph 21
  - [[Samplaski,%202005][Samplaski]] tested robustness of similarity measures by analysing cardinalities in isolation as well as combinations of contiguous cardinalities
** Significance
  - the probability that the observed result might have occurred by chance
  - [[Samplaski,%202005][Samplaski]] paragraph 27
** IdV
   - Interval-difference Vector
   - the difference between the terms of 2 ic-vectors
** SATV
  - Bruchler uses them in [[SATSIM]]
  - derived by comparing the number of instances of each interval-class in a set-class with both the minimum and the maximum number of the corresponding interval-class instances that can be found in any set-class of the same cardinality
  - From a saturation vector one can thus see the degree of saturation of each interval-class vector component.
  - Kussi Appendix 2 
** nC%V
   - n-class percentage vector
   - modification of a [[nCV]] from castren
   - used in [[%RELn]]
** nCV
  - array of numbers corresponding to EMB(A,X)
  - with A running through all set-classes in cardinality class n
* MDS
*** non-metric MDS
    - Shepard (1962), Kruskal (1964a, 1964b)
    - assumes that the distance or proximity values of the matrix are directly related by some unknown function to distances between the objects in some underlying abstract N-dimensional Euclidean space, whose distance metric is the generalized version of the formula familiar from Cartesian geometry, SQRT(x2 + y2 + z2 + ...).
    - distances are symmetric
*** Issues
    1. how do we determine the best [[dimensionality]]?
       - important to minimize the number of dimensions
	 - for visualisation
	 - and parsiomony of explanation
	   - as the number of free parameters increases there become too few constraints on the possible configuration.
       - For a given dimensionality, we obtain two values: [[Stress][stress]] and [[r2]]
       - the number of objects should be at least 3-4 times greater than the highest anticipated dimensionality. [[Samplaski,%202005][samplaski]] paragraph 17
    2. inherent underlying [[asymmetry][asymmetries]]?
       - [[Samplaski,%202005][samplaski]] paragraph 12
       - a number of models for dealing with this
	 - [[ASCAL]]
    3. [[Exemplars]]
*** Stress
    - *goodness of fit measure* 
    - Discrepancies between the actual data values and the derived underlying distances are accounted for in a goodness-of-fit measure called "stress": as the number of dimensions increases, stress decreases, and choosing between configurations of different dimensionalities becomes an issue. (Samplaski)
*** r2
    - r-squared
    - percentage of the variability of the data being explained by the solution
*** elbows
    - plot the stress and r2 values for several dimensionalities
    - look for "elbows" (inflection points) in the plots.
    - If an elbow exists, then the higher-dimensional solutions are not giving significant additional explanation--the plot suddenly flattens out.
    - [[Samplaski,%202005][samplaski]] paragraph 17
*** dimensionality
    - choose dimensionality on the bases of clarity and logical interpretation.
    - one dimension above or below "optimal" as indicated by the stress/r2 values might be better:
      1. if there is a clear interpretation given an added dimension; or
      2. if one configuration is easier to visualize (e.g 3-D vs 4-D solution),
	 - especially in a situation where it is unclear what can be gained in explanatory power by using the extra dimension.
*** asymmetry
    -poor fit can be caused by several factors
*** Exemplars
    - In an MDS analysis of N objects, one of which is an exemplar, the only way to minimize distortion (i.e., stress) is to place the exemplar at the center of the configuration and arrange the other objects around it.
    - [[Samplaski,%202005][samplaski]] note 15
*** INDSCAL
    - deals with idiosyncrasies of subjects ratings
    - takes one matrix per subject
    - [[Samplaski,%202005][samplaski]] paragraph 13
*** ASCAL
     - deals with possible asymmetries underlying the data
     - [[Samplaski,%202005][samplaski]] paragraph 14
*** CA
    - *cluster analysis*
    - (Tversky, 1977; Tversky and Gati, 1982; Tversky and Hutchinson, 1986)
    - helps with problem of highly seperable dimensions
    - There is a family of CA models, but they all work similarly: given a proximity or distance matrix, some method is used to pick the pair of objects most like each other, group them into a single cluster, and derive a new reduced matrix. When the process is finished, the objects will be grouped into a binary tree structure (exactly two branches descend from each node, and the objects are "leaves" at the termini of the final branches), where the distance between any pair of objects is related to the length of the path along the branches separating them.
*** PMDS
    - *Probabalistic MDS*
    - [[Samplaski,%202005][Samplaski]] paragraph 23
    - assumed there is euclidean space
    - onjects are probability distributions
    - variance
    - PMDS is a technique still under development (2005)
    - [[PROSCAL]]
