#+STARTUP: latexpreview
#+STARTUP: indent
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[round]{natbib}
#+LATEX_HEADER: \usepackage[nonumberlist]{glossaries}
#+LATEX_HEADER: \makeglossaries

#+LATEX_HEADER:\newglossaryentry{pc}{name={PC}, description={Pitch Class}}
#+LATEX_HEADER:\newglossaryentry{pcset}{name={PC-Set}, description={Pitch Class Set}}
#+LATEX_HEADER:\newglossaryentry{sc}{name={SC}, description={Set Class}}
#+LATEX_HEADER:\newglossaryentry{nc}{name={nC}, description={Cardinality Class}}
#+LATEX_HEADER:\newglossaryentry{hashnc}{name={\#nC}, description={Size of nC}}
#+LATEX_HEADER:\newglossaryentry{ic}{name={IC}, description={Interval Class}}
#+LATEX_HEADER:\newglossaryentry{tnx}{name={Tn(X)}, description={Transposition}}
#+LATEX_HEADER:\newglossaryentry{ix}{name={I(X)}, description={Inversion}}
#+LATEX_HEADER:\newglossaryentry{tntype}{name={Tn-Type}, description={Transpositional SC-type}}
#+LATEX_HEADER:\newglossaryentry{itype}{name={I-Type}, description={Inversional SC-Type}}
#+LATEX_HEADER:\newglossaryentry{tnitype}{name={TnI-Type}, description={Transpositional/Inversional SC-Type}}
#+LATEX_HEADER:\newglossaryentry{primeform}{name={Prime Form}, description={PC-set representing all members of an SC}}
#+LATEX_HEADER:\newglossaryentry{icv}{name={ICV}, description={Interval-class Vector}}
#+LATEX_HEADER:\newglossaryentry{ncv}{name={nCV}, description={n-class subset vector}}
#+LATEX_HEADER:\newglossaryentry{ncpv}{name={nC\%V}, description={n-class subset percentage vector}}
#+LATEX_HEADER:\newglossaryentry{nsatv}{name={nSATV}, description={n-class subset saturation vector}}
#+LATEX_HEADER:\newglossaryentry{dv}{name={DV}, description={Difference Vector}}
#+LATEX_HEADER:\newglossaryentry{hashx}{name={\#X}, description={Set cardinality}}
#+LATEX_HEADER:\newglossaryentry{hashncv}{name={\#nCV}, description={Vector cardinality}}
#+LATEX_HEADER:\newglossaryentry{trivialform}{name={Trivial Form}, description={SCs 1-1, 11-1 and 12-1}}
\clearpage
\glsaddall
\printglossary
\clearpage
#+TITLE: Evaluation of Pitch-Class Set Similarity Measures for Tonal Analysis (Literature Review)
#+AUTHOR: Nicholas Harley - Masters Thesis UPF
* Introduction
The objectives of the present work are principally concerned with
descriptive modelling of tonality using PC-set theory. In particular,
the analytical potential of set-class similarity measures will be
assessed and evaluated through comparison with similar work. The
tentative goal, therefore, is to present this approach in such a way
as to make it relevant to the wider community of music researchers,
such as those in MIR.

Chapters [[Tonality]]-[[Spatial Models of Tonality]] comprise a literature
review containing background information and some basic
theory. Chapter [[Tonality]] addresses the challenges and problems
involved in descriptive modelling of tonality as a means of
justification for the proposed approach. Chapter [[Pitch-Class Set
Theory]] introduces the basic concepts of PC-set theory including
set-class similarity measures. Chapter [[Multidimensional Scaling]]
gives a basic description of MDS techniques and how they can play a
role in set-class analysis. Chapter [[Spatial Models of Tonality]]
contains a review of the relevant tonal models that exist so as to
give context work that follows.
* Tonality
** Defining Tonality
*** General Definition
Tonality is a notoriously complex musical phenomenon and numerous
definitions have been proposed from a variety of viewpoints. Perhaps
the most general definition is that provided by Hyer \citet(Hyer2013):
"... refers to the systematic arrangements of pitch phenomena and
relations between them." Explanations of tonality have been provided
through many different disciplines (acoustics, music theory,
linguistics, cognitive psychology) and a detailed discussion of these
areas is certainly beyond the scope of this work. However, it is
generally agreed that tonality is an abstract cultural and cognitive
construct that can have many different physical representations.
*** Babbitt's Domains
\citet{Babbitt1965} proposed three domains to categorise different
types of representation of music: acoustic (physical), auditory
(perceived), graphemic (notated). Western music theory provides a
lexicon for describing abstract tonal objects with terms such as note,
chord and key. These objects have a hierarchical relationship and the
meaning of these labels is highly dependent on musical context and the
scale of observation. Musicological descriptions, which constitute the
majority of reasoning about tonaility, reside mainly in the Babbitt's
graphemic domain, although arguably they reflect some aspects of the
other two. Each domain, whilst connected to every other, provides only
a projection of the musical whole and examination of tonality from
just one will most likley result in an incomplete picture. However,
these three domains provide a convenient framework for the discussion
that follows.
** Modelling Tonality
The challenge of mathematically modelling aspects of tonality has been
approached in numerous ways and from different domains. In the
graphemic domain, musicologists and composers have proposed
theoretical models, attempting to rethink tonal theory from a
mathematical perspective. These models employ different branches of
mathematics such as geometry \citep{Tymoczko2012} or group theory
\citep{Ring2011} to describe harmonic structure. From the auditory
domain, cognitive psychologists have built models of tonal induction
based on perceptual ratings of tonal stimuli \citep{Krumhansl1990}.
*** Tonality as Context
Many models approach the concept of tonality as a context, within
which the relations and hierarchies of tonal phenomena can be
understood. A sense of tonality can be induced when musical stimuli
resemble some a priori contextual category. For western music of the
major-minor period, key signatures comprise a collection of categories
that give context to the tonal components of
music. \citet{Martorell2013} identifies three important aspects of
tonality as context: dimensionality (the relatedness of categories),
ambiguity (reference to two or more categories simultaneously) and
timing (the dynamics of tonal context). He highlights the importance
of a models capability to describe these aspects.
*** Tonality in MIR
The MIR community is primarily concerned with the extraction of tonal
descriptors from audio signals such as chord and key estimates. Most
systems use chroma features as a preliminary step, obtained by mapping
STFT or CQ transform energies to chroma bins. Template matching is
used to compare the chroma vectors to a tonal model (contextual
category) using some distance measure. A commonly used tonal model for
key estimation are the KK-profiles \citep{Krumhansl1990} (e.g. in
\citealt{Gomez2006}). Distance measures such as inner product (e.g. in
\citealt{Gomez2006}) and fuzzy distance (e.g. in
\citealt{Purwins2000}) are used to compare vectors. Statistical
methods, such as HMMs, have been used for chord and key tracking
\citep{Chai2005}. Of addition interest in the field is the concept of
musical similarity (for music recommendation, structure analysis,
cover detection etc.). \citet{Foote2000} computed self-similarity
matrices for visualisation of structure by correlating the MFCC
feature vector time-series. \citet{Gomez2006} proposed the application
of this method to tonal feature vectors.
*** Similarity
The importance of defining the similarity or closeness between musical
phenomena, be it theoretical, physical or perceptual, is central to
almost every model of tonality and often leads to a geometric
configuration of tonal objects. The concepts of similarity and
distance is discussed further in Chapter [[Spatial Models of Tonality]]
where a review of spatial models of tonality is given.
** The Semantic Gap
*** Acoustic Domain
\citet{Wiggins2009} discusses, what is referred to in MIR as, the
"Semantic Gap": the inability of systems to achieve success rates
beyond a conspicuous boundary. He examines the fundamental
methodological groundings of MIR in terms of Babbitts three domains,
discussing the limits of each representation and regarding the
discarnate nature of music. He concludes that the audio signal
(acoustic domain) simply cannot contain all of the information that
systems seek to retrieve. He points towards the the auditory domain as
the chief residence of music information and urges for in not to be
overlooked in MIR and wider music research.
*** Graphemic Domain
Furthermore, Wiggins criticises the purely graphemic approach and the
tendency of music research to presuppose musicological
axioms. \citet{Wiggins2012} argues that music (tonal) theory is,
rather than a theory in the scientific sense, a highly developed folk
psychology (internal human theory for explaining common
behaviour). Thus, the rules of music theory are not like scientific
laws but rather abstract descriptions of a specific musical
behaviour. This idea challenges the validity of formalising such rules
in mathematics and prompts the question, "What is actually being
modelled?" He concludes that to apply mathematical models to musical
output alone (scales or chords) without consideration of the musical
mind is a scientific failure.
*** Problems
The two assertions of Wiggins sit contrary to a number of the aspects
of the tonal models discussed in [[Modelling Tonality]]. Firstly, the
major-minor paradigm, upon which so many approaches are based, whilst
certainly possessing cognitive significance, is still a musicological
concept and therefore a misleading basis for both mathematical and
cognitive approaches. A second problem is that of the numerical
methods used by some MIR systems, in particular, distance measures. As
will be discussed in Chapter [[Spatial Models of Tonality]], similarity
(and by extension distance) is a central part of the auditory
domain. MIR systems often uses distance measures from mathematics such
as Mahalanobis \citep{Tzanetakis1999} or Cosine \citep{Foote2000} with
little consideration of their perceptual or musical significance.
** Systematicity
*** The Musical Surface
Having cautioned against a purely musicological approach,
\citet[pp. 481]{Wiggins2009} proposes a compromise: to adopt a
bottom-up approach to music theory, exploring the concepts through
systematic mid-level representations. He states that "methods
starting at, for example, the musical surface of notes is a useful way
of proceeding" The concept of musical surface is illustrated by
\citet[pp. 159]{Huovinen2007} with a metaphor: "...to approach a
musical landscape not by drawing a map, which necessarily confines
itself to a limited set of structurally important features, but by
presenting a bird’s-eye view of the musical surface – an aerial
photograph, as it were, which details the position of every pitched
component."
*** Systematic Description
\citet{Martorell2013} also advocates this mid-level approach,
observing that surface description influences analyitcal observation
and that, for an unbiased view, the researcher must be provided with
the adequate raw materials with which to make more in-depth
observation. Such a systematic, descriptive model would be
fundamentally independent of high level concepts such as chords and
key but, at the same time, capable of capturing
them. \citet{Martorell2013} also discusses the importance of
systematicity in terms of dimensionality, ambiguity and timing. He
finds that models based on the major-minor paradigm are incapable of
adequately describing tonal ambiguity even in some Western music
\citep[chap. 3]{Martorell2013}.

With a systematic description of the musical surface, theories and
models from different domains can be gathered and evaluated together in
the same analytical arena, thus helping to bridge the gap between
traditional musicology, cognitive psychology and MIR.
* Pitch-Class Set Theory
One such method available for systematic description of the musical
surface is Pitch class set theory. PC-set theory is a system for
analysing the pitch content of music. It uses class equivalence
relations to reduce the amount of data required to describe any
sequence of pitches. This chapter will outline the basic principles.
** Pitch Class
Pitch-class set theory uses octave equivalence. In Western equal
temperament (TET), a pitch-class (PC) is an integer representing the
residue class modulo 12 of a pitch /citep(Babbit1955) and indicates
the position of a note within the octave. A PC-set is a collection of
PCs ignoring any repetitions and the order in which they
occur. PC-sets are notated as follows {0,1,2,3,4} with PCs ordered
from lowest to highest as a convention (Example 1). The cardinality of
a set, denoted #S, is the number of PCs it contains (Example 2). There
are 4096 (2^12) unique PC-sets with which any segment of music can be
represented.

#+CAPTION: Notes and corresponding pitch-classes
#+NAME: tab:pitch classes
| Note | C | C# | D | D# | E | F | F# | G | G# | A | A# |  B |
| PC   | 0 |  1 | 2 |  3 | 4 | 5 |  6 | 7 |  8 | 9 | 10 | 11 |

#+NAME: tab:pcset
| Example 1: | PC-set      | Pitch-set | S = {A4,C5,E5,A5} (A minor) |
|            |             | PC-set    | S = {9,0,4,9} = {0,4,9}     |
| Example 2: | Cardinality |           | #S = 3                      |
** Set Classification
Defining equivalence classes of PC-sets further reduces the total
number of tonal objects. A set-class (SC) is a group of PC-sets
related by a transformation or group of transformations. The two types
of transformation commonly used are transposition and inversion. A
transposition, Tn(S), transposes the set, S, by the interval, n, (by
adding n to all PCs, Example 3). An inversion, I(S), inverts the set
S, replacing all PCs with their inverse (12-PC, Example 4). From these
two transformations it is possible to define three types of SC: Tn,
TnI and I, although I-types are not commonly used.

#+NAME: tab:transpostionandinversion
| Example 3: | Transposition | S = {0,4,9}, T3(S) = {3,7,0} = {0,3,7}  |
| Example 4: | Inversion     | S = {0,4,9}, I(S) = {11,7,2} = {2,7,11} |

#+NAME: tab:sctypes
| Transpositional (Tn): | All PC-sets that can be transformed to each |
|                       | by transposition belong to the same class.  |
|                       | There are 348 distinct Tn types.            |
| Inversional (I):      | All PC-sets that can be transformed to each |
|                       | other by inversion belong to the same SC.   |
|                       | There are 197 distinct I types.             |
| Transpositional/      | All PC-sets that can be transformed to each |
| Inversional (TnI):    | other by transposition, inversion or both   |
|                       | belong to the same SC.                      |
|                       | There are 220 distinct TnI types.           |

The Prime Form of a PC-set is a convention for denoting the SC it
belongs to. The convention was introduced by Allan Forte
\citep{Forte1973} for TnI types and has since been adopted by the
majority of theorists. In addition, he devised a system for ordering
TnI-type SCs and assigning to each one a number. For example, the
Forte number 3-11 refers to the 11th SC of cardinality 3. This
convention has been modified for use with Tn types by adding A and B
to the names of inversionally related SCs.

One additional concept is that of cardinality-class (nC), which refers
to all the SCs of cardinality n. Cardinality-class 2 is commonly
referred to as interval-class (IC) and there are 6 distinct
interval-classes.
#+CAPTION: Forte's Prime form and numbering convention
#+NAME: tab:fortename
| PC-set            | {1,4,9} |
| Prime Form (TnI)  | {0,3,7} |
| Prime Form (Tn)   | {0,4,7} |
| Forte Name (TnI)  | 3-11    |
| Forte Name (Tn)   | 3-11B   |

#+CAPTION: Numbers of objects
#+NAME: tab:sctype
| Object type | No. Objects |
|-------------+-------------|
| Pitch       |          88 |
| Pitch set   |        3e26 |
| PC          |          12 |
| PC-set      |        4096 |
| Tn-Type SC  |         348 |
| I-Type SC   |         197 |
| TnI-Type SC |         220 |

#+CAPTION: Cardinality Class
#+NAME: tab:nc
| nC  | Tn | I | TnI |
|-----+----+---+-----|
| 1C  |  1 | 1 |   1 |
| 2C  |  6 | 6 |   6 |
| 3C  | 19 |   |     |
| 4C  |    |   |     |
| 5C  |    |   |     |
| 6C  |    |   |     |
| 7C  |    |   |     |
| 8C  |    |   |     |
| 9C  | 19 |   |     |
| 10C |  6 |   |     |
| 11C |  1 |   |     |
| 12C |  1 |   |     |
** Vector Analysis
*** Membership and Inclusion
Two concepts that are crucial in PC-set theory are membership and
inclusion. Membership of a set is denoted p \in S and means that PC p
is a member of set S (Example 5). Inclusion in a set is denoted Q
\subset S and means that all members of set Q are also members of set
S (Example 6). Q is said to be a subset of S.
#+NAME: tab:membershipandinclusion
| Example 5: | Membership | 4 $\in$ {0,4,9}               |
| Example 6: | Inclusion  | {0,4,9} $\subset$ {0,1,4,5,9} |
*** Embedding Number
\citet{Lewin1979} applied these concepts to SCs to develop his
Embedding Number, EMB(X,Y). Given two SCs, X and Y, EMB(X,Y) is the
number of instances of SC, X, which are included in (are subsets of)
SC, Y (Example 7). X is ring-shifted 11 times and each unique
resulting set which is included in Y adds one to the embedding number.
#+NAME: tab:embeddingnumnber
| Example 7: | Embedding Number | X = {0,4} and Y = {0,4,8} |
|            |                  | so EMB(X,Y) = 3           |
*** Subset Vectors
An n-class subset vector of X, nCV(X), is an array of values of
EMB(A,X) where A is each of the SCs in the cardinality-class, nC
(Example 8). The Interval-Class Vector (ICV) is a special instance of
the nCV with n equal to 2. Vector cardinality, denoted #nCV(X), is the
sum of all the terms in the vector (Example 9). The length of a subset
vector is given by #nC.

Subset vectors form the basis of the majority of analysis performed
by PC-set theorists. In addition, many theorists have proposed
modifications to the basic nCV to suit their specific purposes and
some of these modifications will be discussed in context where
necessary.

#+NAME: tab:subsetvector
| Example 8: | Subset Vector      | S = {0,4,9}                     |
|            |                    | 2CV(S) = ICV(S) = [0 0 1 1 1 0] |
| Example 9: | Vector Cardinality | #ICV(S) = 0+0+1+1+1+0 = 3       |
*** Notation
**** Difference Vector
$$DV(nCV(X),nCV(Y))=\left|nCV(X)-nCV(Y)\right|$$
**** Magnitude
- length vector
$$\left\|nCV(X)\right\|=\sqrt{\sum_{i=1}^{\#nC}{(nCV(X)_{i})^{2}}}$$
**** Unit Vector
$$\hat{nCV(X)}=\frac{nCV(X)}{\left\|nCV(X)\right\|}$$
**** Euclidean Distance
$$d(X,Y)=\sqrt{\sum_{i=1}^{n}{(X_{i}-Y_{i})^{2}}}=\left\|DV(X,Y)\right\|$$
**** Geometric Mean
$$ GM(x,y)=\sqrt{x\times y}$$
$$ GMV(nCV(X),nCV(Y))=[ ]  $$
** Set-Class Similarity
*** Similarity Relations
The assessment of similarity between two SCs has been discussed in the
literature for decades and a large number theoretical models have been
proposed. Different models approache the problem from different
conceptual standpoints and theorists have different opinions about the
contributing factors. All these models are described under the blanket
term "similarity relations". Despite the perennial fascination with
the concept, little or no consensus exits as to what constitutes a
good similarity relation.

\citet{Castren1994} provides a comprehensive and in-depth review of a
large number of similarity relations and categorises them according to
some fundamental principles. Firstly, he distinguishes between methods
that produce binary outcomes and those that produce a range of
values. The former category, termed "plain relations", include Forte's
R-relations \citep{Forte1973} and indicate whether the two SCs are
related in a specific way, which in turn may give some indication of
whether they are similar. The latter category, termed "similarity
measures", indicate a degree of similarity, returning a value from a
known range. This property appears to be more inline with the
perceptual notion of similarity and therefore the focus of this work
shall be exclusively on similarity measures.
*** Similarity Measures
The vast number and diversity of the different approaches to
similarity measures can only be approached by narrowing the focus to a
specific type. Here we will focus on measures that use the Tn and
TnI-type SCs ([[Set Classification]]), and furthermore we will only
consider those methods based on vector analysis ([[Vector
Analysis]]). These measure usually involve the comparison of the SC's
nCVs. Of this (still sizeable) subset, \citet{Castren1994} identifies
two main categories.
#+NAME: tab:measuretypes
| Single nC:      | Single nC measures compare the nCVs of the two SCs   |
|                 | for one particular value of n. Many of the relations |
|                 | in this category compare ICVs (2CVs).                |
| Total Measures: | Total Measures consider the subsets of all           |
|                 | cardinalities contained within in two SCs. All the   |
|                 | relevant nCVs are compared to produce a final value. |

Table 4 shows the majority of the Tn and TnI-Type, vector based
similarity measures from the PC-set theoretical literature. Vector
Type indicates whether the measure compares ICVs or nCVs. Card
(Cardinality) indicates whether the measure is capable of comparing
SCs of different cardinalities while the Measure Type indicates which
of Castren's categories it belongs to. nC indicates it is a Single nC
measure and TOTAL indicates it is a Total Measure. All these measure
are described more thoroughly in [[SC Similarity Measures]].

#+CAPTION: Comparison table of similarity measures
#+NAME: tab:comparisontable
|------------+------------+--------+------+---------|
|            | SIMILARITY | VECTOR |      | MEASURE |
| THEORIST   | MEASURE    | TYPE   | CARD | TYPE    |
|------------+------------+--------+------+---------|
|            | K          | ICV    | SAME | nC      |
|            | SIM        | ICV    | SAME | nC      |
| MORRIS     | ASIM       | ICV    | ANY  | nC      |
|------------+------------+--------+------+---------|
| LORD       | sf         | ICV    | SAME | nC      |
|------------+------------+--------+------+---------|
| TEITELBAUM | s.i.       | ICV    | SAME | nC      |
|------------+------------+--------+------+---------|
|            | IcVD1      | ICV    | ANY  | nC      |
|            | IcVD2      | ICV    | ANY  | nC      |
| ROGERS     | COS        | ICV    | ANY  | nC      |
|------------+------------+--------+------+---------|
|            | AMEMB2     | ICV    | ANY  | nC      |
|            | IcVSIM     | ICV    | ANY  | nC      |
|            | ISIM2      | ICV    | ANY  | nC      |
| ISAACSON   | ANGLE      | ICV    | ANY  | nC      |
|------------+------------+--------+------+---------|
|            | AK         | ICV    | ANY  | nC      |
|            | MEMBn      | nCV    | ANY  | nC      |
|            | TMEMB      | nCV    | ANY  | TOTAL   |
| RAHN       | ATMEMB     | nCV    | ANY  | TOTAL   |
|------------+------------+--------+------+---------|
|            | REL2       | ICV    | ANY  | nC      |
| LEWIN      | REL        | nCV    | ANY  | TOTAL   |
|------------+------------+--------+------+---------|
|            | %RELn      | nC%V   | ANY  | nC      |
|            | T%REL      | nC%V   | ANY  | TOTAL   |
| CASTREN    | RECREL     | nC%V   | ANY  | TOTAL   |
|------------+------------+--------+------+---------|
|            | SATSIM     | nSATV  | ANY  | nC      |
|            | CSATSIM    | CSATV  | ANY  | nC      |
|            | TSATSIM    | nSATV  | ANY  | TOTAL   |
| BUCHLER    | AvgSATSIM  | nSATV  | ANY  | TOTAL   |
|------------+------------+--------+------+---------|
*** Castren's Criteria
In addition to his categorisation, \citet{Castren1994} proposes several
criteria which a good similarity relation should meet. Later, these
criteria will be used in assessing the specific capabilities of
various similarity measures. 

Castren says that a similarity measure should:
- C1: allow comparisons between SCs of different cardinalities
- C2: provide a distinct value for every pair of SCs
- C3: provide a comprehensible scale of values such that
  - C3.1: All values are commensurable
  - C3.2: the end points are not just some extreme values but can be
    meaningfully associated with maximal and minimal similarity.
  - C3.3: The values are integers or other easily manageable numbers
  - C3.4: the degree of discrimination is not too coarse and not
    unrealistically fine
- C4: produce a uniform value for all comparable cases
- C5: observe mutually embeddable subset-classes of all meaningful
  cardinalities
- C6: observe also the mutual embeddable subset-classes not in common
  between the SCs being compared.
** Perceptual Relevance
The many equivalence relations used in PC-set theory give rise to a
highly abstract description of musical objects. Thus, an important
question to be asked is whether these theoretical assumptions and
models of similarity reflect perceptual equivalence. This chapter
contains a summary and discussion of some relevant studies.
*** Octave Equivalence
Pitch is a percept that derives from a particular harmonic structure
and is roughly proportional to the logarithm of the fundamental
frequency. This allows pitch to be modelled as a straight line. Music
psychologists have observed a strong perceptual similarity between
pitches with fundamental frequencies in the ratio of 2:1. This
property of octave similarity leads the straight line model of pitch
to be bent into a helix. Division of the octave into a number of
categories is thought to offer a more efficient cognitive
representation in memory and thus confers evolutionary advantage. The
resulting pitch equivalence classes are implicitly learned through
exposure at an early age. TET has 12 pitch equivalence classes which,
in PC-set theory, are modelled as a circular projection of the pitch
helix. Thus the two most fundamental components of PC-set theory,
i.e. octave equivalence and pitch-class labelling, would appear to
have a solid basis in perception.

\citet{Gibson1988} investigated the perceived similarity of pairs of
chords with varying numbers of octave related pitches. He found that
in general chords with identical PC contents were perceived as more
similar than chords with near identical PC contents, regardless of
the octave. However, in further studies he his findings suggest that
there are other factors that play a significant role
\citep{Gibson1993}.
*** Set-Class Equivalence
Some researchers have attempted to examine whether there is perceived
equivalence between different manifestations of a
PC-set. \citet{KrumhanslSandell1987} presented subjects with sequences
of tones derived by transforming two different PC-sets. They noted
that subjects were able to distinguish between the different sets both
in neutral and musical contexts.  

\citet{Millar1984} investigated the perceptual similarity of different
PC-sets derived from the same set class under TnI
classification. Subjects were presented with three-note melodies and
asked to judge which was equivalent to a reference melody. Some
melodies preserved the SC identity whilst others did not. She found
transpositions to be perceived more similar than inversions and in
addition she discovered that the order of the notes and melodic
contour was a strong factor in perceived similarity.

Some authors have questioned the perceptual relevance of using TnI
equivalence as a basis for set classification. \citet{Deutsch1982}
seems unconvinced by evidence for the perceptual similarity of
inverted intervals. This can be illustrated by the example of major
and minor triads which, while perceptually distinct, are equivalent
under TnI.
*** Perceived vs Theoretical Similarity
A number of studies have been done to ascertain the connection between
perceptual similarity ratings and the theoretical values obtained from
some PC-set similarity measures. A large number of relevant studies
are summarised by \citet{Kuusi2001} and the most significant ones are
mentioned here.

\citet{Bruner1984} used multidimensional scaling on subjects'
similarity ratings between trichords and tetrachords and on the
similarity values obtained from SIM. She compared the 2-dimensional
solutions and found there to be little correlation.

\citet{Gibson1986} investigated non-traditional chords. He compared
subjects' ratings with similarity assessments calculated from Forte's
R-relations and Lord's similarity function. He also concluded there
was little correspondence between the two.

\citet{Stammers1994} compared subjects' ratings of 4 note melodies with
the theoretical values obtained from SIM. She found the ratings of
subjects with more musical training to be more correlated with the SIM
values.

\citet{Lane1997} compared subjects' ratings of pitch sequences with
corresponding values of seven ICV-based similarity measures: ASIM,
MEMB2, REL2, s.i., IcVSIM and AMEMB2 and concluded there to be a
strong relation.

\citet{Kuusi2001} compared subjects' ratings of pentachords with the
values obtained from 9 similarity measures. He found there to be a
connection between aurally estimated ratings and the theoretical
values and concluded that the abstract properties of set-classes do
have some perceptual relevance. He also comments on the way in which
this kind of study is conducted, suggesting that the way in which
subjects are presented with the stimuli has a significant effect on
the outcome.
** PC-set Theory for Analysis
PC-set theory as means for descriptive modelling of tonality is not
widely known outside of highly theoretical circles and the use of
PC-set similarity measures seems mainly restricted to the theorists
who proposed them (for example, \citealt{Isaacson1996}). The basic
premise is simple: a musical piece is segmented and each segment
described by its SC. Similarity measures can be used to assess the
similarity between segments or between a segment and some reference
SC.

\citet{Huovinen2007} used a pentachordal tail segmentation policy
(each successive note defines a segment that includes the preceding
four notes) and compared these segments to comparison sets 7-1
(chromaticism) and 7-35 (diatonicism) using the REL distance
([[REL]]). They claim that the visual results of their analysis "reflect
pertinent aspects of our listening experience"
\citep[pp. 204]{Huovinen}.

\citet[chap. 5.3]{Martorell2013} uses a more systematic approach to
segmentation using multiple time scales. He proposes the class-scape,
a two-dimensional visualisation of a piece of music with time on the
x-axis and segmentation time-scale on the y-axis. A single SC can be
represented by highlighting the segment or alternatively each segment
can be shaded according to its REL distance from a comparison SC. He
emphasises that class-scape is an exploratory tool rather than an
automated analysis system.
* Multidimensional Scaling
Multidimensional scaling (MDS) is a numerical visualisation technique
that, given a matrix of pairwise distances between objects, provides a
geometric configuration of the objects in some abstract space. It
provides an efficient means of observing relationships in large,
complex data sets and the resulting dimensions often give valuable
insight into the data as a whole.
** Non-Metric MDS
Non-Metric MDS was described by \citet{Shepard1962} and it assumes
that the distance matrix values are related to points in an abstract
N-dimensional Euclidean space. An important consideration is that of
the dimensionality of the solution. For comprehension and
visualisation it is important to minimise the number of dimensions
however, there is a trade-off between the number of dimensions and the
accuracy of the model. For a given dimensionality, we obtain two
values: Stress and r^2.
#+NAME: tab:stressr2
| Stress | Stress is a "goodness of fit" measure which characterises   |
|        | the distortion that occurs in a given number of dimensions. |
|        | As the number of dimensions increases the stress decreases. |
| $r^2$  | $r^2$ is the percentage variability of the data being       |
|        | explained by the solution                                   |
By plotting stress against r^2 for a number of dimensionalities is
possible to observe the point at which additional dimensions do not
significantly improve the solution (the "elbow"). Ultimately, the
choice of dimensions should be based on interpretation.
** Cluster Analysis
Cluster analysis (CA) is method for dealing with dimensions that are
highly separable. First, the most similar pair of objects are selected
and grouped together in a cluster. The process is repeated, creating a
binary tree structure. The distance between objects is then related to
their separation along the branches of the tree.
** MDS with Similarity Measures
Using MDS on the values produced by similarity measures is one way to
approach an understanding of the constructs they are measuring. There
are two potentially interesting issues to consider. Firstly, a measure
may be inconsistent with itself, meaning that the geometries it
produces are not "robust" (changing the set of objects changes the
distances between the original set). This kind of problem cannot be
observed through inspection of the values alone. The second issue is
that two different measures that are both self-consistent may produce
very different geometries from the same group of SCs. The question
then is, what exactly do the measures measure?
* Spatial Models of Tonality
** Similarity and Distance
Judgements of similarity form the basis of many cognitive processes
including the perception of tonality. Similarity between two objects
is often conceived as being inversely related to distance between them
in geometric space. For example, some tonal objects (chords, for
example) are perceived as close to one another whereas others are
further apart. In addition, the number of dimensions of the geometric
space is in connection with the number of independent properties that
are relevant for similarity comparisons. \citet{Gardenfors1995}
suggests that humans are naturally predisposed to create spatial
cognitive representations of perceptual stimuli due to the geometric
nature of the world we have evolved to inhabit. Therefore spatial
modelling of tonality, as well as helping to visualise the complex
multidimensional relationships between tonal phenomena, has the
potential to reflect cognitive aspects of the way they are perceived.
** Spatial Representations
Throughout history theorists have proposed many spatial
representations of tonality from different domains. From the graphemic
domain, \citet{Weber} and \citet{Schoenberg} both proposed simple
2-dimensional charts to display the proximity between keys. For
representation of chords, \citet{Riemann} models major and minor
triads as regions in a 2-dimensional space whilst \citet{Tymoczko2011}
proposes a variety high dimensional, non-euclidean chord spaces that
reflect the theoretical principles of voice leading. From the acoustic
domain, \citet{Shepard1982} proposes a five-dimensional model to
represent interval relations between pitches. Some theorists have
attempted to incorporate relations between several levels of tonal
hierarchy into one configuration. The "spiral array" of
\citet{Chew2000a} is a three-dimensional mathematical model which
simultaneously captures the relations between pitches, chords and
keys. The "chordal-regional space" of \citet{Lerdahl2001a} models the
relations between chords within a certain key.
** Cognitive Psychology
The auditory domain has been addressed through cognitive psychology
by \citet{Krumhansl1990} who used the probe-tone methodology
\citep{Krumhansl1979} to establish major and minor key profiles
(12-dimensional vectors containing the perceptual stability ratings of
each of the 12 pitch classes within a major or minor context). These
profiles, know as Krumhansl-Kessler profiles (KK-profiles), show the
hierarchy of pitches in major and minor keys. Correlating each of the
24 major and minor profiles produced a matrix of pairwise distances
which was fed to a dimensional scaling algorithm. The resulting
geometrical solution was found to have a double circular property
(circle of fifths and relative-parallel relations) which can be
modelled as the surface a 3D torus. Many spatial models of tonality
have this double circular property whether it is implicit
\citep{Weber,Schoenberg} or stated explicitly \citep{Lerdahl2001a}.
** Set-Class Spaces
Most of these models are limited to description of music in the
major-minor paradigm and are not capable of generalising beyond the
"western common practice". PC-set theory, once again, provides a
possible means to generalise to any kind of pitch-based music. By
considering a collection of tonal objects described by SCs, a
geometric space can be constructed to model their relations based on
some theoretical principle. Some PC-set theorists have proposed
explicit geometric spaces to model relations between SCs. The
distances in these spaces are expressed by models of similarity based
on voice leading \citep{Cohn2003,Tymoczko2012} or ICVs and the Fourier
transform \citep{Quinn2006, Quinn2007}. However, these models are only
designed to represent SCs of one cardinality-class at a time and
cannot model the relations between arbitrary collections of pitches.

Alternative spatial models are provided by the implicit geometries of
the values produced by the SC similarity measures discussed in [[PC-Set
Similarity]]. As mentioned in [[MDS with Similarity Measures]], MDS can be
used on values produced by similarity measure to create a geometric
space. \citet{Kuusi2001} and \citet{Samplaski2005a} both applied MDS to
the values produced from a variety of similarity measures. Samplaski
used TnI-type SCs while Kuusi used Tn-type. They both found reasonably
low-dimensional solutions and attempted to interpret each of the
dimensions. Kuusi interpreted three dimensions as corresponding to
chromaticism, wholetoneness and pentatonicism. Samplaski made similar
observations but found some dimensions in the higher-dimensional
spaces difficult to interpret. Nevertheless, he concluded that values
from similarity measure tend to agree (with some exceptions) and that
they measure constructs relating to familiar scales (diatonic,
hexatonic, octatonic, etc.).
* Similarity Measure Selection
In this section, the large number of SC similarity measures from the
literature will be discussed in relation to Castren's criteria (see
[[Castren's Criteria]]) in order to gauge their suitability for use in
systematic surface description models. The most suitable measures will
be subjected to a more thorough analysis over the course of the work.
** Criteria
#+CAPTION: Castrens Criteria
#+NAME: tab:criteria
|------------+----+----+------+------+------+------+----+----+----|
| SIMILARITY | C1 | C2 | C3.1 | C3.2 | C3.3 | C3.4 | C4 | C5 | C6 |
| MEASURE    |    |    |      |      |      |      |    |    |    |
|------------+----+----+------+------+------+------+----+----+----|
| s.i.       |    |    |      |      | X    | X    |    |    |    |
| sf         |    |    |      |      | X    | X    | X  |    |    |
| IcVSIM     | X  | X  |      |      |      | X    |    |    |    |
| ISIM2      | X  | X  |      |      |      | X    |    |    |    |
| K          | X  | X  |      |      | X    | X    | X  |    |    |
| SIM        | X  | X  |      |      | X    | X    | X  |    |    |
| MEMBn      | X  | X  |      |      | X    | X    | X  |    |    |
| AMEMB2     | X  | X  | X    |      |      |      |    |    |    |
| ASIM       | X  | X  | X    | X    |      | X    | X  |    |    |
| IcVD1      | X  | X  | X    | X    |      | X    | X  |    |    |
| IcVD2      | X  | X  | X    | X    |      | X    |    |    |    |
| COS        | X  | X  | X    | X    |      | X    |    |    |    |
| ANGLE      | X  | X  | X    | X    |      | X    |    |    |    |
| AK         | X  | X  | X    | X    |      | X    | X  |    |    |
| SATSIM     | X  | X  | X    |      |      |      |    |    |    |
| CSATSIM    | X  | X  | X    |      |      |      |    |    |    |
| REL2       |    |    |      |      |      |      |    |    |    |
| %RELn      | X  | X  | X    | X    | X    | X    | X  |    |    |
| TMEMB      | X  | X  |      |      | X    |      | X  | X  |    |
| ATMEMB     | X  | X  | X    | X    |      | X    | X  | X  |    |
| TSATSIM    | X  | X  | X    | X    |      | X    |    | X  |    |
| AvgSATSIM  | X  | X  | X    | X    |      | X    |    | X  |    |
| REL        | X  | X  | X    | X    |      | X    | X  | X  |    |
| T%REL      | X  | X  | X    | X    | X    | X    | X  | X  |    |
| RECREL     | X  | X  | X    | X    | X    | X    | X  | X  | X  |
|------------+----+----+------+------+------+------+----+----+----|
** Cardinality
Measures which fail to meet criteria C1, i.e. that cannot compare SCs
of different cardinalities, are clearly inadequate for systematic
analysis of music, which might require the comparison of any two
arbitrary segments regardless of how many PCs they contain. Both
s.i. ([[s.i.]]) and sf ([[sf]]) were proposed specifically for SCs of the same
cardinality and so will be excluded from further discussion. Some
other measures which were intended to compare SCs of different
cardinalities nonetheless have problems. Many measures such as SIM
([[SIM]]) and K ([[K]]) give unintuitive values when the cardinalities of the
SCs being compared differ greatly and, in addition, the range of
values produced depends on the cardinality of the sets (failure to
meet criteria C3.1). Measures of this type will also be excluded.
** SC-type
An important consideration when using similarity measures is the type
of SC being compared. Many of the measures are designed for comparison
of TnI-type SCs, however, owing to issues riased in [[Perceptual
Relevance]] regarding the perceptual relevance of invertionally related
sets, here, measures will be selected for use with Tn-type SCs. This
means that the measure should be able to discrimate between
inversionally related sets. All the measures which exclusivly consider
interval content in the comparison procedure can automatically be
discounted, as inversionally related sets have identical ICVs.
** Measure Type
Although many theorists have suposed that interval-class subsets are
of paramount importance in similarity judgments, no thorough
investigation has been carried out as to the exact perceptual
significance of subset cardinality. Single nC measures presupose that
subsets of one particular cardinality contribute to similarity above
all others. In the interest of systematicity, we will not make this
assumption instead assuming that subsets of all cardinalities are
equally relevant and should be considered. Similarity measures that
consider all subset cardinalities meet criteria C5 and are total
measures. These total measures will selected for further investigation
throughout the work.
** Trivial Forms
Three of the 351 Tn-type SCs are known as trivial forms: 1-1, 11-1 and
12-1. Due to their lack of musical or harmonic significance, these SCs
are usually excluded from the work of SC-theorists. However, it is
important that they be included in any systematic description and that
their similarity to other sets be given a meaningful value. The next
chapter will discuss each of the total measures and specify how each
of the trivial forms is to be dealt with if it was not made explicit
by the theorist. 

The total measures which will be discussed make comparisons based on
the subset content of a set. SC 1-1, which has no subsets, is rarely
accounted for in such measures and in these cases a simple method will
be used: Comparisons involving X = 1-1 and Y will be given the value
1/#Y. Thus, the value will be the ratios of the cardinalities with 1
indicating maximum similarity.
#+CAPTION: Trivial Forms
#+NAME: tab:trivialforms
|  1-1 | {0}                         |
| 11-1 | {0,1,2,3,4,5,6,7,8,9,10}    |
| 12-1 | {0,1,2,3,4,5,6,7,8,9,10,11} |
* Total Measures
In this chapter each of the total measures examined in more detail and
assessed terms of its particular abilities and discriminatory power.
** Rahn: ATMEMB
Details on how to calculate ATMEMB are give in [[ATMEMB]]. In his analysis
of the measure, Castren concludes that "divisor term is flawed,
resulting in values suggesting suspiciously high degrees of
dissimilarity between SCs of clearly different cardinalities. The
general reliability and usefulness of the measure is difficulty to
determine" \citep[pp. 89]{Castren1994}. The trivial forms 11-1 and
12-1 are accommodated explicitly by the fomulation of
\citet{Rahn1979}, however SC 1-1 is not and thus values will be
obtained using the method specified in [[Trivial Forms]].
** Lewin: REL
Details on how to calculate REL are given in [[REL]]. From the basic
equation it is possible to define three different formulations
depending on the exact nature of SUB(X). In each formulation the
trivial forms 11-1 and 12-1 are accomodated. The three formulations
are as follows:
1) SUB(X) consists of the concatenated nCVs from 2 to 12. Here
   comparisons involving SC 1-1 will be evaluated with the method
   specified in [[Trivial Forms]].
2) SUB(X) consists of the concatenated nCVs from 1 to 12 (1CV(X)
   = #X). This formulation accommodates SC 1-1.
3) \citet{Martorell2013} specifies an alternative formulation where
   SUB(X) begins with the ICV (2CV) followed by the concatenated nCVs
   from 1 to 12. This formulation accommodates SC 1-1.
** Buchler: AvgSATSIM and TSATSIM
Details on how to calculate AvgSATSIM and TSATSIM are given in
[[AvgSATSIM]] and [[TSATSIM]] respectively. Comparisons involving SC 1-1 are
not accommodated and thus the method specified in [[Trivial Forms]] will
be used to provide values. Comparisons involving SCs 11-1 and 12-1 are
accommodated except for the single comparison that involves both. This
is because their MAX_{n}(#X) and MIN_{n}(#X) vectors are equal and
thus all terms of the nSATVs are 0. The value for this comparison will
be set to 0 (indicating maximal similarity). For comparisons involving
ICs the value will be given by SATSIM_{2}(X,Y) (see [[SATSIM_{n}]]).
** Castren: T%REL and RECREL
Details on how to calculate T%REL and RECREL are given in [[T%REL]] and
[[RECREL]] respectively. Comparisons involving SCs 11-1 and 12-1 are
accommodated in both by Castren's formulation. Comparisons involving
SC 1-1 will be given values by the method specified in [[Trivial
Forms]].

- Castren comments that some T%REL values are too high.
- The basic algorithm provided by Castren for calculating RECREL is
  not feasible for large sets. Compaisons of such sets require tables
  of pre-computed branch values.
** Scale of Values
The values of each measure will be adjusted to the same scale for
comparability by the same method as \citet[pp. 48]{Kuusi2001}). This
scale is from 0 to 100 with with 0 indicating maximum similarity. The
modified values will be signalled by adding the symbol "prime" to the
name.
- ATMEMB-prime(X,Y) = (1-ATMEMB(X,Y))*100
- REL-prime(X,Y) = (1-REL(X,Y))*100
- AvgSATSIM-prime(X,Y) = AvgSATSIM(X,Y)*100
- TSATSIM-prime(X,Y) = TSATSIM(X,Y)*100
- T%REL-prime(X,Y) = T%REL(X,Y)
- RECREL-prime(X,Y) = RECREL(X,Y)
* Analysis of Chord Dictionary
- generated a dictionary of chord types from mirex
- convert chord types into Tn-Type SCs
- examine values
- Analyse corpora: what chords are used in what kind of music
- billboard data set
- which measure best handle/discriminate between these chords
** Chords as PC sets
- Chord types taken from mirex
- scale types
- cadence types

#+CAPTION: Chord types and their SCs
#+NAME: tab:chordSC
|------------+--------------------+------------+-------|
|            | PC-Set             | Forte Name |       |
| Chord      | (Prime Form)       | (Tn-type)  | index |
|------------+--------------------+------------+-------|
| maj        | {0,4,7}            | 3-11B      |    25 |
| min        | {0,3,7}            | 3-11A      |    24 |
| dim        | {0,3,6}            | 3-10       |    23 |
| aug        | {0,4,8}            | 3-12       |    26 |
| sus4       | {0,2,7}            | 3-9        |    22 |
| sus2       | {0,2,7}            | 3-9        |    22 |
|------------+--------------------+------------+-------|
| maj7       | {0,1,5,8}          | 4-20       |    57 |
| min7       | {0,3,5,8}          | 4-26       |    64 |
| hdim7      | {0,2,5,8}          | 4-27A      |    65 |
| 7          | {0,3,6,8}          | 4-27B      |    66 |
| dim7       | {0,3,6,9}          | 4-28       |    67 |
| min(7)     | {0,1,4,8}          | 4-19A      |    55 |
| aug(7)     | {0,3,4,8}          | 4-19B      |    56 |
| maj(9)     | {0,2,4,7}          | 4-22A      |    59 |
| min(9)     | {0,2,3,7}          | 4-14A      |    46 |
| maj6       | {0,3,5,8}          | 4-26       |    64 |
| min6       | {0,1,5,8}          | 4-20       |    57 |
| sus4(7)    | {0,2,6,7}          | 4-16B      |    51 |
| sus4(b7)   | {0,2,5,7}          | 4-23       |    61 |
|------------+--------------------+------------+-------|
| 9          | {0,2,4,6,9}        | 5-34       |   129 |
| maj9       | {0,1,3,5,8}        | 5-27A      |   116 |
| min9       | {0,3,5,7,8}        | 5-27B      |   117 |
|------------+--------------------+------------+-------|
| V-I/IV-I   | {0,1,3,5,8}        | 5-27A      |   116 |
| V7-I       | {0,1,3,5,6,8}      | 6-Z25A     |   176 |
| V-IV       | {0,2,4,6,7,9}      | 6-33B      |   189 |
|------------+--------------------+------------+-------|
| Pentatonic | {0,2,4,7,9}        | 5-35       |   130 |
| Wholetone  | {0,2,4,6,8,10}     | 6-35       |   192 |
| Diatonic   | {0,1,3,5,6,8,10}   | 7-35       |   276 |
| Octatonic  | {0,1,3,4,6,7,9,10} | 8-28       |   322 |
|------------+--------------------+------------+-------|

* Class Scape
- from martorell
- visualise examples of corpora using class-scape
* MDS
- 
- Visualisation of values using MDS
* Structure
- cadential sets
- autocorrelation
- self-similarity matrix
- Analysis of structure
* Latex Stuff
\clearpage
\bibliographystyle{plainnat}
\bibliography{/Users/nick/Documents/MendeleyDesktop/library.bib}

\clearpage
\appendix
* SC Similarity Measures
** MORRIS
*** K
Presented in \citet[pp. 448]{Morris1979}, the K measure gives the
number of intervals-classes (dyad-classes) shared by two SCs, X and Y.
$$ K(X,Y)= \sum_{i=1}^{6}{MIN(x_{i},y_{i})} $$
#+NAME: tab:k
| SC Type:        | TnI                |
| Cardinality:    | Any                |
| Vector Type:    | ICV                |
| Max Similarity: | 55                 |
| Min Similarity: | 0                  |
| Average Value:  | 10                 |
| No. Values:     | 35                 |
| Criteria Met:   | C1,C2,C3.3,C3.4,C4 |
| I-related:      | No                 |
| Z-related:      | No                 |
- Problems: scale of values not the same for all value groups.
*** SIM
Presented in \citet[pp. 446]{Morris1979}, SIM compares the ICVs of
two SCs (the value is the cardinality of the DV).
$$SIM\left(X,Y\right)=\sum_{i=1}^{6}\left|x_{i}-y_{i}\right|$$
or
$$SIM\left(X,Y\right)=\#DV\left(ICV\left(X\right),ICV\left(Y\right)\right)$$
SIM is a function of K:
$$SIM(X,Y) = \#ICV(X) + \#ICV(Y) - 2.K(X,Y)$$
#+NAME: tab:sim
| SC Type:        | TnI                |
| Cardinality:    | Any                |
| Vector Type:    | ICV                |
| Max Similarity: | 0                  |
| Min Similarity: | 65                 |
| Average Value:  | 13                 |
| No. Values:     | 44                 |
| Criteria Met:   | C1,C2,C3.3,C3.4,C4 |
| I-related:      | No                 |
| Z-related:      | No                 |
- Problems: scale not the same for all value groups. course resolution
  when cardinalities differ greatly
*** ASIM
Presented in \citet[pp. 450]{Morris1979}, ASIM (Absolute SIM) is a
scaled version of SIM to address criteria C3.1.
$$ASIM\left(X,Y\right)=\frac{SIM\left(X,Y\right)}{\#ICV\left(X\right)+\#ICV\left(Y\right)}$$
#+NAME: tab:asim
| SC Type:        | TnI                     |
| Cardinality:    | Any                     |
| Vector Type:    | ICV                     |
| Max Similarity: | 0                       |
| Min Similarity: | 1                       |
| Average Value:  | 0.42                    |
| No. Values:     | 79                      |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4,C4 |
| I-related:      | No                      |
| Z-related:      | No                      |
Problems: Fixed the scale of values, but still coarse resolution when
cardinalities differ greatly. Scaling is done as the last step.
** LORD
*** sf
Presented in \cite[pp. 93]{Lord1981}, sf (Similarity Function) is
similar to SIM but developed independently. sf is a subset of SIM:
$$sf\left(X,Y\right)=\frac{\#DV\left(ICV\left(X\right),ICV\left(Y\right)\right)}{2}=\frac{SIM(X,Y)}{2}$$
#+NAME: tab:sf
| SC Type:        | TnI          |
| Cardinality:    | Same         |
| Vector Type:    | ICV          |
| Max Similarity: | 0            |
| Min Similarity: | 9            |
| Average Value:  | 3            |
| No. Values:     | 10           |
| Criteria Met:   | C3.3,C3.4,C4 |
| I-related:      | No           |
| Z-related:      | No           |
** TEITELBAUM
*** s.i.
Presented in \citet[pp. 88]{Teitelbaum1965}, s.i. (Similarity Index)
is the Euclidean distance between the carteasian coordinates defined
by the ICVs of two SCs. This is equivelant to the magnitude of the
difference vector.
$$s.i.(X,Y)=\sqrt{\sum_{i=1}^{6}(x_{i}-y_{i})^{2}}=\left\|DV(ICV(X),ICV(Y))\right\|$$
#+NAME: tab:si
| SC Type:        |       TnI |
| Cardinality:    |      Same |
| Vector Type:    |       ICV |
| Max Similarity: |      1.41 |
| Min Similarity: |      8.49 |
| Average Value:  |      2.85 |
| No. Values:     |        31 |
| Criteria Met:   | C3.3,C3.4 |
| I-related:      |        No |
| Z-related:      |        No |
- Same cardinality only
- Z-related sets not compared
** ROGERS
*** IcVD_{1}
Presented in \citet{Rogers1992}, IcVD_{1} (Distance Formula 1) is a
modification of SIM ([[SIM]]). The ICV components are scaled before being
summed. IcVD_{1} is related to Castren's %REL_{2} ([[%REL_{n}]]):
\%REL_{2}(X,Y) = IcVD_{1}(X,Y)\times 50.  

$$IcVD_{1}(X,Y)=\#DV\left(\frac{ICV(X)}{\#ICV(X)},\frac{ICV(Y)}{\#ICV(Y)}\right)$$

#+NAME: tab:icvd1
| SC Type:        | TnI                     |
| Cardinality:    | Any                     |
| Vector Type:    | ICV                     |
| Max Similarity: | 0                       |
| Min Similarity: | 2                       |
| Average Value:  | 0.59                    |
| No. Values:     | 140                     |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4,C4 |
| I-related:      | No                      |
| Z-related:      | No                      |
*** IcVD_{2}
Presented in \citet{Rogers1992}, IcVD_{2} (Distance Formula 2) is
similar to s.i. ([[s.i.]]), but instead returns the Euclidean distance
between the ends of the normalised ICVs.
$$IcVD_{2}(X,Y)=\left\|DV(\hat{ICV(X)},\hat{ICV(Y)})\right\|$$
#+NAME: tab:icvd2
| SC Type:        | TnI                  |
| Cardinality:    | Any                  |
| Vector Type:    | ICV                  |
| Max Similarity: | 0                    |
| Min Similarity: | 1.41                 |
| Average Value:  | 0.54                 |
| No. Values:     | 133                  |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4 |
| I-related:      | No                   |
| Z-related:      | No                   |
- Problems: does not produce uniform values for comparable cases
*** Cos(\theta)
Presented in \citet{Rogers1992}, Cos\theta, gives the cosine of the
angle between the ICVs in six-dimensional euclidean space. As the
angle decreases the similarity approaches 1.
$$Cos\theta(X,Y)=\frac{ICV(X)\cdot ICV(Y)}{\left\|ICV(X)\right\|\times\left\|ICV(Y)\right\|}$$
#+NAME: tab:costheta
| SC Type:        | TnI                  |
| Cardinality:    | Any                  |
| Vector Type:    | ICV                  |
| Max Similarity: | 1                    |
| Min Similarity: | 0                    |
| Average Value:  | 0.81                 |
| No. Values:     | 92                   |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4 |
| I-related:      | No                   |
| Z-related:      | No                   |
- Problems: C4
** RAHN
*** AK
Presented in /citet[pp. 489]{Rahn1979}, AK is an absolute or adjusted
version of Morris' K ([[K]]), addressing the C3.1 criteria. AK is related
to Morris' ASIM: AK(X,Y)=1-ASIM(X,Y).
$$AK\left(X,Y\right)=\frac{2K\left(X,Y\right)}{\#ICV\left(X\right)+\#ICV\left(Y\right)}$$
#+NAME: tab:ak
| SC Type:        | TnI                     |
| Cardinality:    | Any                     |
| Vector Type:    | ICV                     |
| Max Similarity: | 1                       |
| Min Similarity: | 0                       |
| Average Value:  | 0.58                    |
| No. Values:     | 78                      |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4,C4 |
| I-related:      | No                      |
| Z-related:      | No                      |
- Problems: single scale of values (C4), but poor discrimination for
  some value groups.
*** MEMB_{n}
Presented in \citet[pp. 492]{Rahn1979}, MEMB_{n} (Mutual Embedding
Number) compares the nCVs of two SCs for one nC at a time. It meausres
the mutual embedding of subsets such that only non-zero components of
the nCVs contribute. By setting n = 2 (MEMB_{2}) it compares ICVs.
$$MEMB_{n}\left(X,Y\right)=\sum_{i=1}^{\#nC}{nCV(X)_{i}+nCV(Y)_{i}}$$
such that nCV(X)_{i}>0 and nCV(Y)_{i}>0. 
#+NAME: tab:membn
| SC Type:        | TnI or Tn          |
| Cardinality:    | Any                |
| Vector Type:    | nCV                |
| Max Similarity: | 121                |
| Min Similarity: | 0                  |
| Average Value:  | 30                 |
| No. Values:     | 79                 |
| Criteria Met:   | C1,C2,C3.3,C3.4,C4 |
| I-related:      | Yes*               |
| Z-related:      | Yes*               |
- Problems: does not produce uniform scale of values for all value
  groups.
*** TMEMB
Presented in \citet[pp. 492]{Rahn1979}, TMEMB (Total Mutual Embedding
Number) counts the mutually embedded subsets of every
cardinality. TMEMB is a total measure.
$$TMEMB\left(X,Y\right)=\sum_{n=2}^{12}MEMB_{n}\left(X,Y\right)$$
#+NAME: tab:tmemb
| SC Type:        | TnI or Tn        |
| Cardinality:    | Any              |
| Vector Type:    | nCV              |
| Max Similarity: | 6118             |
| Min Similarity: | 0                |
| Average Value:  | 131              |
| No. Values:     | 877              |
| Criteria Met:   | C1,C2,C3.3,C4,C5 |
| I-related:      | Yes              |
| Z-related:      | Yes              |
- Problems: Different value scales for different value groups
*** ATMEMB
Presented in \citet[pp. 494]{Rahn1979}, ATMEMB (Adjusted Total Mutual
Embedding Number) is a scaled version of TMEMB to address criteria
C3.1 (like SIM and ASIM; A and AK). ATMEMB is a total measure.
$$ATMEMB\left(X,Y\right)=\frac{TMEMB\left(X,Y\right)}{2^{\#X}+2^{\#Y}-\left(\#X+\#Y+2\right)}$$
#+NAME: tab:atmemb
| SC Type:        |                  TnI or Tn |
| Cardinality:    |                        Any |
| Vector Type:    |                        nCV |
| Max Similarity: |                          1 |
| Min Similarity: |                          0 |
| Average Value:  |                       0.45 |
| No. Values:     |                        101 |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4,C4,C5 |
| I-related:      |                        Yes |
| Z-related:      |                        Yes |
** ISAACSON
*** AMEMB2
Proposed by \citet[pp. 8]{Isaacson1990}, AMEMB_{2} (Adjusted MEMB_{2})
is a scaled version MEMB_{2} ([[MEMB_{n}]]), measuring the mutual
embedding of ICs.

$$AMEMB_{2}=\frac{2 \times
MEMB_{2}(X,Y)}{\left(\#X\left(\#X-1\right)+\#Y\left(\#Y-1\right)\right)}$$
#+NAME: tab:amemb2
| SC Type:        | TnI |
| Cardinality:    | Any |
| Vector Type:    | ICV |
| Max Similarity: | 1   |
| Min Similarity: | 0   |
| Average Value:  |     |
| No. Values:     |     |
| Criteria Met:   |     |
*** IcVSIM
Presented in \citet[pp. 18]{Isaacson1990}, IcVSIM (Interval-Class
Vector Similarity Relation) is the standard deviation of the entries
in the ICVs of two SCs. IcVSIM is a scaled version of
s.i. ([[s.i.]]). IdV_{i} is the ith term in the vector defined by
ICV(X)-ICV(Y) and $\overline{DV}$ is the average (mean) of its
entries.
$$IcVSIM(X,Y)=\sqrt{\frac{\sum(IdV_{i}-\overline{IdV})^{2}}{6}}$$
#+NAME: tab:icvsim
| SC Type         | TnI        |
| Cardinality:    | Any        |
| Vector Type:    | ICV        |
| Max Similarity: | 0          |
| Min Similarity: | 3.64       |
| Average Value:  | 1.2        |
| No. Values:     | 121        |
| Criteria Met:   | C1,C2,C3.4 |
| I-related:      | No         |
| Z-related:      | No         |
*** ISIM2
Presented in \citet{Isaacson1996}, ISIM2 is a scaled version of IcVSIM
([[IcVSIM]]). The squre root is taken of each term in the ICVs. Isaacson
argues that each additional instance of an IC contributes less to
similitude. However, \citet{Samplaski2005a} found ISIM2 to be
inconsistent with itself when applying MDS to the values produced.
#+NAME: tab:isim2
| SC Type         | TnI        |
| Cardinality:    | Any        |
| Vector Type:    | ICV        |
| Max Similarity: |            |
| Min Similarity: |            |
| Average Value:  |            |
| No. Values:     |            |
| Criteria Met:   | C1,C2,C3.4 |
*** ANGLE (Isaacson & Scott)
\citet{Scott1998} propose a geometric method which is identical to
that of Cos/theta ([[Cos(\theta)]]) but instead gives the size of the
angle in degrees. $$ANGLE(X,Y) = \arccos{Cos\theta(X,Y)}$$
#+NAME: tab:isim2
| SC Type         | TnI                  |
| Cardinality:    | Any                  |
| Vector Type:    | ICV                  |
| Max Similarity: |                      |
| Min Similarity: |                      |
| Average Value:  |                      |
| No. Values:     |                      |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4 |
| I-related:      | No                   |
| Z-related:      | No                   |
** LEWIN
*** REL
Presented in \citet{Lewin1979}, REL compares the nCVs of two SCs for
all the nCs. Like MEMB_{n} ([[MEMB_{n}]]), REL only considers non-zero
entries however, this is achieved by multiplication (taking the
geometric mean) of corresponding nCV terms.

$$REL(X,Y)=\frac{\sum_{i=1}^{p}{\sqrt{SUB(X)_{i}\times SUB(Y)_{i}}}}{\sqrt{\#SUB(X)\times \#SUB(Y)}}$$

$$REL(X,Y)=\frac{\#GMV(SUB(X),SUB(Y))}{GM(\#SUB(X),\#SUB(Y))}$$

where SUB(X) consists of concatenated nCVs and has a length p.
#+NAME: tab:rel
| SC Type:        | TnI or Tn                  |
| Cardinality:    | Any                        |
| Vector Type:    | nCV                        |
| Max Similarity: | 1                          |
| Min Similarity: | 0                          |
| Average Value:  | 0.57                       |
| No. Values:     | 91                         |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4,C4,C5 |
| I-related:      | Yes                        |
| Z-related:      | Yes                        |
*** REL_{2}
\citet{Rahn1979} suggested a number of manifestations of the basic REL
concept including REL_{2} which measures only intervallic similarity.
$$ REL_{2}(X,Y)\frac{2\times\sum\sqrt{(x_{i}y_{i})}}{\sqrt(\#X(\#X-1)\#Y(\#Y-1))} $$
#+NAME: tab:rel
| SC Type:        | TnI                  |
| Cardinality:    | Any                  |
| Vector Type:    | ICV                  |
| Max Similarity: | 1                    |
| Min Similarity: | 0                    |
| Average Value:  |                      |
| No. Values:     |                      |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.4 |
** CASTREN
*** Castren's Difference Vector
Castren specifies a different type of DV, which we shall call cDV to
distinguish it from the regular DV. It consistes of two rows,
$cDV_{x}(X,Y)=X-Y$ and $cDV_{y}(X,Y)=Y-X$. Any negative values in
either of the rows are set to zero.  In addition Castren defines the
weighted difference vector (wcDV) of two vectors X and Y as:
$$wcDV=\frac{cDV(X,Y)}{\#cDV(X,Y)}\times 100$$
*** nC%V
Presented in \citet{Castren1994} for use in %REL_{n}, nC%V(X) (n-class
subset percentage vector) gives the percentage subset-class contents
of an SC, X. The 2C%V is the Interval percentage vector.
$$nC\%V(X)=\frac{nCV(X)}{\#nCV(X)}\times 100$$
*** %REL_{n}
Presented in \citet{Castren1994}, %REL_{n} (Percentage Relation) is a
modification of sf ([[sf]]) using the nC%Vs ([[nC%V]]) instead of
ICVs. %REL_{n} can be used as a stand-alone measure, however it is
primarily intended as an intermediate step in T%REL and RECREL ([[T%REL]]
and [[RECREL]]). $$\%REL_n(X,Y)=\frac{\#DV(nC\%V(X),nC\%V(Y))}{2}$$
#+NAME: tab:%reln
| SC Type         | TnI or Tn                    |
| Cardinality:    | Any                          |
| Measure Type:   | Single nC                    |
| Vector Type:    | nC%V                         |
| Max Similarity: | 0                            |
| Min Similarity: | 100                          |
| Average Value:  | 30                           |
| No. Values:     | 85                           |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.3,C3.4,C4 |
| I-related:      | Sometimes                    |
| Z-related:      | Sometimes                    |
*** T%REL
Presented in \citet{Castren1994}, T%REL (Total Percentage Relation) is
the mean average of the vlaues of %REL_{n} for all values of $n$ from $2$
to $m$ where, if $\#X\neq\#Y$, $m = MIN(\#X,\#Y)$ else $m=\#X-1$.
$$T\%REL(X,Y)=\frac{\sum_{n=2}^{m}{\%REL_n\left(X,Y\right)}}{m-1}$$
#+NAME: tab:t%rel
| SC Type:        | TnI or Tn                       |
| Cardinality:    | Any                             |
| Measure Type:   | Total                           |
| Vector Type:    | nC%V                            |
| Max Similarity: | 0                               |
| Min Similarity: | 100                             |
| Average Value:  | 63                              |
| No. Values:     | 79                              |
| Criteria Met:   | C1,C2,C3.1,C3.2,C3.3,C3.4,C4,C5 |
| I-related:      | Yes                             |
| Z-related:      | Yes                             |
*** RECREL
Presented in \citet{Castren1994}, RECREL (Recursive Relation)
recursively compares the subsets and subsets of subsets of two SCs
using %REL_{n} ([[%REL_{n}]]). The comparison procedure is quite
complicated and potentially involves evaluating %REL_{n} thousands of
times.
#+NAME: tab:t%rel
| SC Type:        | TnI or Tn |
| Cardinality:    | Any       |
| Measure Type:   | Total     |
| Vector Type:    | nC%V      |
| Max Similarity: | 0         |
| Min Similarity: | 100       |
| Average Value:  |           |
| No. Values:     | 89        |
| Criteria Met:   | All       |
| I-related:      | Yes       |
| Z-related:      | Yes       |
** BUCHLER
*** nSATV
Presented in \citet[chap. 2.3]{Buchler1997} nSATV(X) (Saturation
Vector) is a dual vector consisting of two rows, nSATV_{A}(X) and
nSATV_{B}(X). It shows extent to which an SC is saturated with
subclasses of cardinality n. The steps for computing nSATV(X) are
as follows:

1. Compute the nCVs for all SCs of cardinality #X.
2. Find the minimum and maximum values for each vector position. These
   values form vectors $Max_{n}(\#X)$ and $Min_{n}(\#X)$.
3. Compute the following two vectors:
   $MaxMinus=DV(nCV(X),Max_{n}(\#X))$ and $MinPlus=DV(nCV(X),Min_{n}(\#X))$
4. $nSATV_{A}(X)_{i}=MIN(MaxMinus_{i},MinPlus_{i})$ and
   $nSATV_{B}(X)_{i}=MAX(MaxMinus_{i},MinPlus_{i})$
5. If $MaxMinus_{i}=MinPlus_{i}$, $nSATV_{A}(X)_{i}=MaxMinus_{i}$
   and $nSATV_{B}(X)_{i}=MinPlus_{i}$
*** SATSIM_{n}
Presented in \citet[chap. 2.4]{Buchler1997}, SATSIM_{n} (Saturation
Similarity index) compares the nSATVs of two SCs and involves the
following steps:
1) Calculate nSATV(X) and nSATV(Y)
2) Calculate the vectors nSATV_{row}(X) and nSATV_{row}(Y).
3) The function "row" maps the MaxMinus values of one nSATV to the
   MaxMinus values of the other. If nSATV_{A}(X)_{i} is a MaxMinus
   value and nSATV_{A}(X)_{i} is also a MaxMinus value, row = A
   (nSATV_{row}(X)_{i} = nSATV_{A}(X)_{i}), otherwise row = B.
4) Finally SATSIM_{n}(X,Y) is given by the formula:

$$SATSIM_{n}(X,Y)=\frac{\#DV(nSATV_{A}(X),nSATV_{row}(Y))+\#DV(nSATV_{A}(Y),SATV_{row}(X))}{\#DV(nSATV_{A}(X),SATV_{B}(X))+\#DV(SATV_{A}(Y),SATV_{B}(Y))}$$
*** CSATSIM                                                      :noexport:
- cyclic saturation similarity
**** Description
- uses CSATV
*** AvgSATSIM
Presented in \citet[chap. 2.10]{Buchler1997}, AvgSATSIM (Average
Saturation Similarity index) is the mean of SATSIM_{n} values where
$m=MIN(\#X,\#Y)$.

$$ AvgSATSIM(X,Y)=\frac{\sum_{n=2}^{m-1}{SATSIM_{n}(X,Y)}}{m-2}$$
*** TSATSIM
Presented in \citet[chap. 2.10]{Buchler1997}, TSATSIM (Total
Saturartion Vector Similarity index) is an extension of
SATSIM_{n}. TSATSIM is the quotient of the sum of all SATSIM_{n}
numerators and denominators for all values of n from 2 to m-1 where
$m=MIN(\#X,\#Y)$.
